//@version=6
indicator(title = 'MA1 + MA2 + MA2', shorttitle = 'MA1 + MA2 + MA3', overlay = true)

ma_1_normal = ta.rma(close, 13)
ma_1 = request.security(syminfo.tickerid, '60', ta.rma(close, 13))

ma_2_normal = ta.rma(close, 55)
ma_2 = request.security(syminfo.tickerid, '60', ta.rma(close, 55))

ma_3_normal = ta.rma(close, 13)
ma_3 = request.security(syminfo.tickerid, '45', ta.rma(close, 55))

plot( ma_1, title = 'MA 1', color = color.blue, linewidth = 1)
plot( ma_2, title = 'MA 2', color = color.purple, linewidth = 1)
plot( ma_3, title = 'MA 3', color = color.yellow, linewidth = 1)
